[package]
name = "resonate"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "6.0.0"
iced = "0.13.1"
rusqlite = "0.33.0"
thirtyfour = "0.35.0"
tokio = { version = "1.43.0", features = ["full"] }
